version: "3.9"

services:
  app:
    build: .
    container_name: fastify_app
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    environment:
      DATABASE_URL: "postgres://postgres:password@postgres:5432/mydb"
    networks:
      - fastify_network

  postgres:
    image: postgres:16
    container_name: find_a_friend_postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: findafriend
      POSTGRES_PASSWORD: findafriend
      POSTGRES_DB: findafriend
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - fastify_network

volumes:
  postgres_data:

networks:
  fastify_network:
    driver: bridge
